name: Deploy function using github actions

# On closer of a pr will delete the corespondent stage environment 
on:
  pull_request:
    types: [closed]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: yarn install
      uses: actions/setup-node@v1
    - name: serverless remove env
      uses: serverless/github-action@master
      with:
        args: remove --stage pr$(jq --raw-output .number "$GITHUB_EVENT_PATH")
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

